name: cismobile
description: M24 Application .
version: 0.1.6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0

  # architecture
  get:
  get_storage:

  # database
  sembast:

  # api
  http:
  html:

  # misc
  shimmer:
  cached_network_image:
  async:
  enhanced_future_builder:
  lazy_load_refresh_indicator:
  flutter_statusbarcolor:
  mime:
  package_info: ^0.4.0+16

  # download
  dio:
  path_provider:
  ext_storage: ^1.0.3
  permission_handler: ^5.1.0+2
  open_file: ^3.0.3

  # localization
  flutter_localizations:
    sdk: flutter
  global_configuration: ^1.5.0

  # migrate from bloc
  flutter_secure_storage: ^4.2.0
  font_awesome_flutter:
  image_picker: ^0.6.7+22
  photo_view: ^0.11.1
  extended_image: 1.3.1-dev
  image_editor: ^1.0.0
  simple_ocr_plugin: ^0.1.1
  connectivity: ^3.0.3
  shared_preferences: ^0.5.12+4
  multi_image_picker: ^4.8.00
  flutter_map: ^0.12.0
  latlong: ^0.6.1
#  location: ^3.2.4
  photo_manager: ^1.2.0
  intl: ^0.17.0
  grouped_list: ^4.0.0
  sticky_grouped_list: ^1.3.0
  collection: ^1.15.0
#  location_web: ^1.0.1
  flutter_svg: ^0.19.3
  flutter_staggered_grid_view: ^0.3.0
  timeline_tile: ^2.0.0
  google_fonts: ^1.1.2
  flutter_showcase: ^0.1.0
  dropdown_search: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - lang/
    - assets/icon/
    - assets/images/
  uses-material-design: true
